version: '3'

services:
  app:
    container_name: myApp
    image: "php:5.6"
    volumes:
      - ".:/app"
    working_dir: /app
    entrypoint: php -d date.timezone=UTC -f /app/src/index.php
#    entrypoint: php -d date.timezone=UTC -f /app/vendor/bin/phpunit
